[project]
name = "claude-cli-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncio>=3.4.3",
    "pandas>=2.3.1",
    "pathlib>=1.0.1",
    "ujson>=5.10.0",
]
